---
# tasks file for roles/tradeoffer
- name: Ensure docker service is running
  become: true
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Clone repo from git
  ansible.builtin.git:
    repo: https://github.com/AnnaKlyshnikova/task1-Docker-Ansible-Vagrant.git
    dest: /srv/tradeoffer
    version: main
    force: yes

- name: Create workdir
  become: true
  ansible.builtin.copy:
    src: /srv/tradeoffer/
    dest: /opt/tradeoffer/
    owner: vagrant
    group: vagrant
    mode: '0755'
    remote_src: yes

- name: Start Tradeoffer
  community.docker.docker_compose_v2:
    project_src: /opt/tradeoffer
    files:
      - compose.yml

  

